package com.mark43.practice;

import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for the Report class.
 *
 * Do not edit this file. Make these tests pass by editing Report.java.
 */
class ReportTest {

    private static final Long ID = 1L;
    private static final Long DEPARTMENT_ID = 100L;
    private static final String REPORT_NUMBER = "RPT-2024-00193";
    private static final String REPORT_TITLE = "Theft from Vehicle";
    private static final Instant CREATED = Instant.parse("2024-03-15T14:30:00Z");

    @Test
    void constructorAssignsAllFields() {
        Report report = new Report(ID, DEPARTMENT_ID, REPORT_NUMBER, REPORT_TITLE, false, CREATED);

        assertEquals(ID, report.getId());
        assertEquals(DEPARTMENT_ID, report.getDepartmentId());
        assertEquals(REPORT_NUMBER, report.getReportNumber());
        assertEquals(REPORT_TITLE, report.getReportTitle());
        assertEquals(CREATED, report.getCreatedDateUtc());
    }

    @Test
    void newReportIsNotSealedWhenConstructedAsFalse() {
        Report report = new Report(ID, DEPARTMENT_ID, REPORT_NUMBER, REPORT_TITLE, false, CREATED);

        assertFalse(report.isSealed());
    }

    @Test
    void newReportIsSealedWhenConstructedAsTrue() {
        Report report = new Report(ID, DEPARTMENT_ID, REPORT_NUMBER, REPORT_TITLE, true, CREATED);

        assertTrue(report.isSealed());
    }

    @Test
    void sealMarksUnsealedReportAsSealed() {
        Report report = new Report(ID, DEPARTMENT_ID, REPORT_NUMBER, REPORT_TITLE, false, CREATED);
        assertFalse(report.isSealed());

        report.seal();

        assertTrue(report.isSealed());
    }
}
