package com.mark43.practice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * Tests for SQL Chapter 1: Writing Queries.
 *
 * Each test loads the schema and seed data, then runs your .sql file
 * from src/main/resources/queries/. If the result rows match what's
 * expected, the test passes.
 *
 * Do not edit this file. Make these tests pass by editing the .sql
 * files under src/main/resources/queries/.
 */
class QueriesTest {

    private JdbcTestHarness db;

    @BeforeEach
    void setUp() {
        db = new JdbcTestHarness();
        db.executeScript("/schema.sql");
        db.executeScript("/seed.sql");
    }

    @AfterEach
    void tearDown() {
        db.close();
    }

    @Test
    void exercise1_reportsByDepartment() {
        List<Map<String, Object>> rows = db.executeQueryFromResource("/queries/01_reports_by_department.sql");

        assertEquals(5, rows.size(),
                "Expected 5 active reports in department 42 (report 15 is deleted, report 20 is in another dept).");

        // Ordered DESC by created_date_utc, so RPT-2024-005 (Apr 1) comes first.
        assertEquals(14L, rows.get(0).get("id"));
        assertEquals("RPT-2024-005", rows.get(0).get("report_number"));

        assertEquals(13L, rows.get(1).get("id"));
        assertEquals("RPT-2024-004", rows.get(1).get("report_number"));

        assertEquals(12L, rows.get(2).get("id"));
        assertEquals(10L, rows.get(3).get("id"));
        assertEquals(11L, rows.get(4).get("id"));
    }

    @Test
    void exercise2_q1SubmittedReports() {
        List<Map<String, Object>> rows = db.executeQueryFromResource("/queries/02_q1_submitted_reports.sql");

        assertEquals(2, rows.size(),
                "Expected 2 reports: SUBMITTED + dept 42 + active + created in Q1 2024.");

        // Sorted ASC by created_date_utc, so RPT-2024-001 (Mar 1) comes first.
        assertEquals("RPT-2024-001", rows.get(0).get("report_number"));
        assertEquals("RPT-2024-004", rows.get(1).get("report_number"));
    }

    @Test
    void exercise3_casesWithOfficersJoin() {
        List<Map<String, Object>> rows = db.executeQueryFromResource("/queries/03_cases_with_officers.sql");

        assertEquals(6, rows.size(),
                "Expected 6 active cases in dept 42 WITH an assigned officer "
                        + "(case 4 has no officer -- excluded by inner JOIN; case 7 is deleted).");

        // First row: most recent active case with an officer (CS-2024-008, Mar 25).
        assertEquals("CS-2024-008", rows.get(0).get("case_number"));
        assertEquals("Bob", rows.get(0).get("first_name"));
        assertEquals("Jones", rows.get(0).get("last_name"));
        assertEquals("B-003", rows.get(0).get("badge_number"));
    }

    @Test
    void exercise4_casesWithOptionalOfficerLeftJoin() {
        List<Map<String, Object>> rows = db.executeQueryFromResource("/queries/04_cases_with_optional_officer.sql");

        assertEquals(7, rows.size(),
                "Expected 7 active cases in dept 42, including case 4 (no officer assigned).");

        // The case with NULL officer is CS-2024-004 (created 2024-03-15).
        // Sorted DESC: position 0 is CS-2024-008 (Mar 25), position 1 is CS-2024-006 (Mar 20),
        // position 2 is CS-2024-004 (Mar 15) -- the one with the NULL officer.
        Map<String, Object> caseWithNullOfficer = rows.get(2);
        assertEquals("CS-2024-004", caseWithNullOfficer.get("case_number"));
        assertNull(caseWithNullOfficer.get("first_name"),
                "Case CS-2024-004 has no assigned officer; LEFT JOIN should give NULL for the officer's first_name.");
        assertNull(caseWithNullOfficer.get("last_name"));
    }

    @Test
    void exercise5_caseCountByStatus() {
        List<Map<String, Object>> rows = db.executeQueryFromResource("/queries/05_cases_by_status.sql");

        assertEquals(3, rows.size(),
                "Expected 3 status groups: CLOSED, OPEN, PENDING (each appears in dept 42's active cases).");

        // ORDER BY status (alphabetical): CLOSED, OPEN, PENDING.
        assertEquals("CLOSED", rows.get(0).get("status"));
        assertEquals(1L, ((Number) rows.get(0).get("case_count")).longValue());

        assertEquals("OPEN", rows.get(1).get("status"));
        assertEquals(5L, ((Number) rows.get(1).get("case_count")).longValue(),
                "Should be 5 OPEN cases (1, 2, 4, 6, 8). Case 7 is CLOSED and deleted; doesn't count.");

        assertEquals("PENDING", rows.get(2).get("status"));
        assertEquals(1L, ((Number) rows.get(2).get("case_count")).longValue());
    }

    @Test
    void exercise6_topThreeOpenCases() {
        List<Map<String, Object>> rows = db.executeQueryFromResource("/queries/06_top_open_cases.sql");

        assertEquals(3, rows.size(),
                "Expected exactly 3 rows -- LIMIT 3 caps the result regardless of how many OPEN cases exist.");

        // Top 3 OPEN cases by created_date_utc DESC:
        // CS-2024-008 (Mar 25), CS-2024-006 (Mar 20), CS-2024-004 (Mar 15).
        assertEquals("CS-2024-008", rows.get(0).get("case_number"));
        assertEquals("CS-2024-006", rows.get(1).get("case_number"));
        assertEquals("CS-2024-004", rows.get(2).get("case_number"));
    }
}
