package com.mark43.practice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Tests for the ReportService class.
 *
 * Do not edit this file. Make these tests pass by editing ReportService.java.
 */
class ReportServiceTest {

    private ReportRepository repository;
    private ReportService service;

    @BeforeEach
    void setUp() {
        repository = new ReportRepository();
        service = new ReportService(repository);
    }

    private Report validReport() {
        return new Report(1L, 100L, "RPT-2024-001", "Theft", false, Instant.parse("2024-01-01T00:00:00Z"));
    }

    @Test
    void validReportIsSavedAndReturned() {
        Report report = validReport();
        Report result = service.createReport(report);

        assertSame(report, result, "createReport should return the saved report");
        assertEquals(1, repository.saveCount(), "Repository should have been called once");
    }

    @Test
    void nullReportThrows() {
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> service.createReport(null));
        assertEquals("report cannot be null", ex.getMessage());
        assertEquals(0, repository.saveCount(), "Repository should not be called when input is invalid");
    }

    @Test
    void nullTitleThrows() {
        Report report = new Report(1L, 100L, "RPT-001", null, false, Instant.now());
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> service.createReport(report));
        assertEquals("reportTitle cannot be empty", ex.getMessage());
    }

    @Test
    void emptyTitleThrows() {
        Report report = new Report(1L, 100L, "RPT-001", "", false, Instant.now());
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> service.createReport(report));
        assertEquals("reportTitle cannot be empty", ex.getMessage());
    }

    @Test
    void whitespaceOnlyTitleThrows() {
        Report report = new Report(1L, 100L, "RPT-001", "   ", false, Instant.now());
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> service.createReport(report));
        assertEquals("reportTitle cannot be empty", ex.getMessage());
    }

    @Test
    void nullDepartmentIdThrows() {
        Report report = new Report(1L, null, "RPT-001", "Theft", false, Instant.now());
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> service.createReport(report));
        assertEquals("departmentId is required", ex.getMessage());
    }

    @Test
    void reportNumberMissingPrefixThrows() {
        Report report = new Report(1L, 100L, "INC-001", "Theft", false, Instant.now());
        IllegalArgumentException ex = assertThrows(IllegalArgumentException.class,
                () -> service.createReport(report));
        assertEquals("reportNumber must start with RPT-", ex.getMessage());
    }

    @Test
    void repositoryNotCalledWhenValidationFails() {
        Report report = new Report(1L, 100L, "INC-001", "Theft", false, Instant.now());
        assertThrows(IllegalArgumentException.class, () -> service.createReport(report));
        assertEquals(0, repository.saveCount(), "Repository must not be called when validation fails");
    }
}
