import { describe, it, expect } from 'vitest';
import {
    formatReportNumber,
    isEditableStatus,
    getReportTitle,
    getOfficerName,
    getReportsByStatus,
    type ReportResponse,
    type Officer,
} from './reports';

/**
 * Tests for TypeScript Chapter 1: Types and Functions.
 *
 * Do not edit this file. Make these tests pass by editing src/reports.ts.
 */

describe('formatReportNumber', () => {
    it('zero-pads the sequence to six digits', () => {
        expect(formatReportNumber(42, 7)).toBe('RPT-42-000007');
    });

    it('uses the department id verbatim', () => {
        expect(formatReportNumber(100, 12345)).toBe('RPT-100-012345');
    });
});

describe('isEditableStatus', () => {
    it('returns true for DRAFT', () => {
        expect(isEditableStatus('DRAFT')).toBe(true);
    });

    it('returns true for REJECTED and RECALLED', () => {
        expect(isEditableStatus('REJECTED')).toBe(true);
        expect(isEditableStatus('RECALLED')).toBe(true);
    });

    it('returns false for SUBMITTED and APPROVED', () => {
        expect(isEditableStatus('SUBMITTED')).toBe(false);
        expect(isEditableStatus('APPROVED')).toBe(false);
    });
});

describe('getReportTitle', () => {
    it('returns the report title when present', () => {
        const report = makeReport({ reportTitle: 'Theft from Vehicle' });
        expect(getReportTitle(report)).toBe('Theft from Vehicle');
    });

    it('falls back to "Untitled Report" when title is null', () => {
        const report = makeReport({ reportTitle: null });
        expect(getReportTitle(report)).toBe('Untitled Report');
    });
});

describe('getOfficerName', () => {
    it('returns "FirstName LastName" for an officer', () => {
        const officer: Officer = {
            id: 100,
            firstName: 'Jane',
            lastName: 'Doe',
            badgeNumber: 'B-001',
        };
        expect(getOfficerName(officer)).toBe('Jane Doe');
    });

    it('returns "Unassigned" when officer is null', () => {
        expect(getOfficerName(null)).toBe('Unassigned');
    });
});

describe('getReportsByStatus', () => {
    it('returns only reports whose approvalStatus matches', () => {
        const reports: ReportResponse[] = [
            makeReport({ id: 1, approvalStatus: 'DRAFT' }),
            makeReport({ id: 2, approvalStatus: 'SUBMITTED' }),
            makeReport({ id: 3, approvalStatus: 'SUBMITTED' }),
            makeReport({ id: 4, approvalStatus: 'APPROVED' }),
        ];

        const submitted = getReportsByStatus(reports, 'SUBMITTED');

        expect(submitted).toHaveLength(2);
        expect(submitted.map(r => r.id)).toEqual([2, 3]);
    });

    it('returns an empty array when no reports match', () => {
        const reports: ReportResponse[] = [
            makeReport({ approvalStatus: 'DRAFT' }),
        ];

        expect(getReportsByStatus(reports, 'APPROVED')).toEqual([]);
    });
});

// --- helpers ---

function makeReport(overrides: Partial<ReportResponse>): ReportResponse {
    return {
        id: 1,
        reportNumber: 'RPT-42-000001',
        reportTitle: 'Test Report',
        approvalStatus: 'DRAFT',
        assignedOfficerId: null,
        createdDateUtc: '2024-01-01T00:00:00Z',
        isSealed: false,
        ...overrides,
    };
}
