package com.mark43.practice;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.QueryParam;
import java.lang.reflect.Method;
import java.lang.reflect.Parameter;
import java.time.Instant;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for the ReportResource class.
 *
 * Do not edit this file. Make these tests pass by editing ReportResource.java.
 */
class ReportResourceTest {

    private ReportStore store;
    private ReportResource resource;

    private static final Report REPORT_1 = new Report(1L, 100L, "RPT-001", "Theft", false, Instant.parse("2024-01-01T00:00:00Z"));
    private static final Report REPORT_2 = new Report(2L, 100L, "RPT-002", "Assault", false, Instant.parse("2024-01-02T00:00:00Z"));
    private static final Report REPORT_3 = new Report(3L, 200L, "RPT-003", "Burglary", false, Instant.parse("2024-01-03T00:00:00Z"));

    @BeforeEach
    void setUp() {
        store = new ReportStore();
        store.save(REPORT_1);
        store.save(REPORT_2);
        store.save(REPORT_3);
        resource = new ReportResource(store);
    }

    @Test
    void classIsAnnotatedWithPathReports() {
        Path path = ReportResource.class.getAnnotation(Path.class);
        assertNotNull(path, "ReportResource should be annotated with @Path");
        assertEquals("/reports", path.value(), "@Path on ReportResource should be \"/reports\"");
    }

    @Test
    void getByIdHasGetAndPathAnnotations() throws Exception {
        Method method = ReportResource.class.getDeclaredMethod("getById", Long.class);
        assertNotNull(method.getAnnotation(GET.class), "getById should be annotated with @GET");
        Path pathAnnotation = method.getAnnotation(Path.class);
        assertNotNull(pathAnnotation, "getById should be annotated with @Path");
        assertEquals("/{id}", pathAnnotation.value(), "@Path on getById should be \"/{id}\"");
    }

    @Test
    void getByIdParameterIsAnnotatedWithPathParamId() throws Exception {
        Method method = ReportResource.class.getDeclaredMethod("getById", Long.class);
        Parameter param = method.getParameters()[0];
        PathParam annotation = param.getAnnotation(PathParam.class);
        assertNotNull(annotation, "getById's parameter should have @PathParam");
        assertEquals("id", annotation.value(), "@PathParam value should be \"id\"");
    }

    @Test
    void getByIdReturnsReportFromStore() {
        Report result = resource.getById(1L);
        assertEquals(REPORT_1, result);
    }

    @Test
    void listByDepartmentHasGetAnnotation() throws Exception {
        Method method = ReportResource.class.getDeclaredMethod("listByDepartment", Long.class);
        assertNotNull(method.getAnnotation(GET.class), "listByDepartment should be annotated with @GET");
    }

    @Test
    void listByDepartmentParameterIsAnnotatedWithQueryParam() throws Exception {
        Method method = ReportResource.class.getDeclaredMethod("listByDepartment", Long.class);
        Parameter param = method.getParameters()[0];
        QueryParam annotation = param.getAnnotation(QueryParam.class);
        assertNotNull(annotation, "listByDepartment's parameter should have @QueryParam");
        assertEquals("departmentId", annotation.value(), "@QueryParam value should be \"departmentId\"");
    }

    @Test
    void listByDepartmentReturnsOnlyMatchingReports() {
        List<Report> result = resource.listByDepartment(100L);
        assertEquals(2, result.size(), "Department 100 should have 2 reports");
        assertTrue(result.contains(REPORT_1));
        assertTrue(result.contains(REPORT_2));
    }

    @Test
    void createReportHasPostAnnotation() throws Exception {
        Method method = ReportResource.class.getDeclaredMethod("createReport", Report.class);
        assertNotNull(method.getAnnotation(POST.class), "createReport should be annotated with @POST");
    }

    @Test
    void createReportSavesAndReturnsTheReport() {
        Report newReport = new Report(99L, 100L, "RPT-099", "Vandalism", false, Instant.parse("2024-05-01T00:00:00Z"));
        Report result = resource.createReport(newReport);
        assertEquals(newReport, result);
        assertEquals(newReport, store.findById(99L));
    }
}
